#!/bin/bash

g++ client.cpp ../logic/logic.cpp msg.cpp -o client -I/usr/include/libnl3 -lnl-3 -lnl-genl-3 -lnl-route-3
g++ server.cpp ../logic/logic.cpp msg.cpp -o server -I/usr/include/libnl3 -lnl-3 -lnl-genl-3 -lnl-route-3
